<a href="https://colab.research.google.com/github/HammadAliKhanweb3/30-Days-React-Challenge/blob/main/sentimental_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("train.txt",sep=";",header=None,names=["text","emotion"])

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [ ]:
unique_emotions = df["emotion"].unique()
emotion_numbers = {}

i=0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i+=1

df["emotion"] = df["emotion"].map(emotion_numbers)
print(repr(df.loc[1, 'text']))

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:



df['text'] = df['text'].apply(lambda x : x.lower())

df.loc[15]['text']

'i do not feel reassured anxiety is on each side'

In [ ]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [ ]:
df['text'] = df['text'].apply(remove_punc)
df.loc[15]['text']

'i do not feel reassured anxiety is on each side'

In [ ]:

def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [ ]:
df.loc[15]['text']

'i do not feel reassured anxiety is on each side'

In [ ]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [ ]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

def remove_stop(txt):
  text = nlp(txt)
  cleaned = []
  for token in text:
    if not token.is_stop:
      cleaned.append(token.text)
  return ' '.join(cleaned)

df["text"] = df['text'].apply(remove_stop)

In [ ]:
df.loc[1]['text']

'feeling hopeless damned hopeful cares awake'

In [ ]:
df.head()

                                          text  emotion
0                           nt feel humiliated        0
1  feeling hopeless damned hopeful cares awake        0
2     m grabbing minute post feel greedy wrong        1
3    feeling nostalgic fireplace know property        2
4                              feeling grouchy        1